# This file was generated by GoReleaser. DO NOT EDIT.
cask "labelsync@rc" do
  version "0.1.0-rc.3"

  on_macos do
    on_intel do
      sha256 "d33062db381688ed38ddfbcf47a05c9c692d82df8daaffd8d1705eaabd3238d4"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a3c2a4d4131b9af1c9baec8e53c844761df15a975761a00cdf804dd371bd24d"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3f5d33c2f2359c39037c7eda7c101c2c7bda316dd551d0f40aec76921c74e95b"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "02630a8db08d5cd443c0829adcf4cf1f73455455c00f43bebdbebbfbc5af6e11"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_linux_arm64.tar.gz"
    end
  end

  name "labelsync@rc"
  desc "A Github label synchronization tool"
  homepage "https://github.com/specsnl/labelsync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "labelsync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/labelsync"]
    end
  end

  # No zap stanza required

end
