# This file was generated by GoReleaser. DO NOT EDIT.
cask "labelsync@rc" do
  version "0.1.0-rc.5"

  on_macos do
    on_arm do
      sha256 "b5046bf00f0332889fcab3c5c72931d2452df36c6159d8ef87b00ebee7415a96"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9b4cdf5d9e24bd9382de6642a124eb835d7752f6d6d7242d18d235fff372113e"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "72778a547b36850cfba1a61e1a4c8b67c70f9a715213383856331936d2f3b341"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a6ffd6f1628215b986998466c8eb6dc069d123d9c457bc899da29f3b5d104704"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_linux_amd64.tar.gz"
    end
  end

  name "labelsync@rc"
  desc "A Github label synchronization tool"
  homepage "https://github.com/specsnl/labelsync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "labelsync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/labelsync"]
    end
  end

  # No zap stanza required
end
