# This file was generated by GoReleaser. DO NOT EDIT.
cask "labelsync" do
  version "0.1.0-rc.1"

  on_macos do
    on_intel do
      sha256 "e78bd44e5080ed77208e8354ea3f78525715fd979d672dee539f1edce5074bff"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "03c18752ff0a574848b79faa49cb0d38791ef3f5b446957a0d59feaeeed1de8f"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cabb30a9ab3ed312f7d49cd5a2225f1e0c5f5e4d62666f62bf73488984f7892b"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2a3db6257caf6c1f129f3589f5e7676a48ba3dffb04326a51d1cd5500e56d0b7"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_linux_arm64.tar.gz"
    end
  end

  name "labelsync"
  desc "A Github label synchronization tool"
  homepage "https://github.com/specsnl/labelsync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "labelsync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/labelsync"]
    end
  end

  # No zap stanza required

end
