# This file was generated by GoReleaser. DO NOT EDIT.
cask "labelsync@rc" do
  version "0.1.0-rc.4"

  on_macos do
    on_intel do
      sha256 "1d42690ab5fd659d91e6f5a99494eb65a51a7237c1e726ad9b9f876a9870980f"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dbf3dcbccd756b5f0685ddde31d312c6a0762a69b5310cd44ec66ee377778be0"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c9b69afd90d41f716481fcaab9f077d8f2a7fea8380717f0d07ad2e00094c7cd"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cbb8e7ca57f03feca5b6f78c69d5ab3ae3643df6453da231dd7351639c10bb62"
      url "https://github.com/specsnl/labelsync/releases/download/v#{version}/labelsync_linux_arm64.tar.gz"
    end
  end

  name "labelsync@rc"
  desc "A Github label synchronization tool"
  homepage "https://github.com/specsnl/labelsync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "labelsync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/labelsync"]
    end
  end

  # No zap stanza required

end
