# This file was generated by GoReleaser. DO NOT EDIT.
cask "specs@rc" do
  version "0.0.14-rc.1"

  on_macos do
    on_arm do
      sha256 "84d22092833673900cd8fdaea273a645ddebcb8dcdc825b90fb0814ac54484d0"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0e9d4da8f323f521e83da8a4f0c75e3692cd9a6d9ca447fb39fc8ad5212fce56"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9ead64d79277497930e9c485b56d9e465d0369cd27cf0c9e75c2b6ee8ee73f05"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7b25a5eb3341d89886b20a684edb53fb2ec1be1b8609e0e0e659fe537275b8a2"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_linux_amd64.tar.gz"
    end
  end

  name "specs@rc"
  desc "General-purpose developer CLI"
  homepage "https://github.com/specsnl/specs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/specs"]
    end
  end

  # No zap stanza required
end
