# This file was generated by GoReleaser. DO NOT EDIT.
cask "specs" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "1a2190789ab7b33da247ebc75b5d9ff6e3f6585e44042e1d87ea6c278d08917d"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ca9369935fbf5d30e973e4e0d443fe154d8bca1445d46225b66d467f04ca12d8"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a14b22099654400db1c70d6118a45a3b53801750e5b482e592bbe881494b8a4f"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "971e71d99efc0e9e849bf1916bfc998b68e65164fb14c940d4201be062389685"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_linux_arm64.tar.gz"
    end
  end

  name "specs"
  desc "General-purpose developer CLI"
  homepage "https://github.com/specsnl/specs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/specs"]
    end
  end

  # No zap stanza required

end
