# This file was generated by GoReleaser. DO NOT EDIT.
cask "specs@rc" do
  version "0.0.14-rc.2"

  on_macos do
    on_arm do
      sha256 "4f4e2d9310365d439b0adcd9354773e70e4eea3d9e1853cfe13a40589febc1da"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b694d763c748fef941196262fa64e75e1be92f02a220768cf4fd2e5c9fd129b9"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f402899c23206767c6607e2e1e1fc33cacf5387c8f4a6b4a2d76fc2f6f348c1a"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "277e9bb5d9663920c487b4b930b9ac710f72a13770050f8e23bd99eac8d52d11"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_linux_amd64.tar.gz"
    end
  end

  name "specs@rc"
  desc "General-purpose developer CLI"
  homepage "https://github.com/specsnl/specs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/specs"]
    end
  end

  # No zap stanza required
end
