# This file was generated by GoReleaser. DO NOT EDIT.
cask "specs" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "829e6a689a6294692a17df556e4cd93909d2a833478f92be2c657d008df1c51a"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "03c1d813a8e89aaf4957da0e0bec9c5d9000fb9e6d7f8c1eca220fe8a90440d1"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2a048e36550b0a1f997d87e6fdca1dc107a47ee895e6634b4dc81804499a9561"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "94c6cd67bce9470d5d9032635dbfa7918103ef944ced859ab19d462d4c3b7479"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_linux_arm64.tar.gz"
    end
  end

  name "specs"
  desc "General-purpose developer CLI"
  homepage "https://github.com/specsnl/specs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/specs"]
    end
  end

  # No zap stanza required

end
