# This file was generated by GoReleaser. DO NOT EDIT.
cask "specsdeployd" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "be8446b3b92c2a7ae00ff77360fad4f6639b0a71e8ec5153a522e12a3dc38fcb"
      url "https://github.com/specsnl/specsdeployd/releases/download/v#{version}/specsdeployd_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "75421c69be30309cbb553c15d48e52aab1669115f1d21fca4ae49be2aa7711d5"
      url "https://github.com/specsnl/specsdeployd/releases/download/v#{version}/specsdeployd_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6fadd597dcac43fe0ab38f0521c55a9805375fa4c3162efbaaabab7033be58ff"
      url "https://github.com/specsnl/specsdeployd/releases/download/v#{version}/specsdeployd_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "25de2a980bfedde344c42e8ac86c7fd67f7ece5a5434e0f26ad061238e8edafb"
      url "https://github.com/specsnl/specsdeployd/releases/download/v#{version}/specsdeployd_linux_amd64.tar.gz"
    end
  end

  name "specsdeployd"
  desc "The deploy agent of the Specs golden images"
  homepage "https://github.com/specsnl/specsdeployd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specsdeployd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/specsdeployd"]
    end
  end

  # No zap stanza required
end
