# This file was generated by GoReleaser. DO NOT EDIT.
cask "specs" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "58d364bfa548f511777e0c2761fe0ee4b44826d2edc8252eff7205c52e2b8057"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb3ce9ed9cfb36c070421167b1fd6769e85b6f8585448c34dba7e20400d5cd41"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "006d3309859fa57655b52057d6309d75ff642747cb7024106964cb5d67e9019a"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "18395307c4b605d6e158aa4ed12edf76eeb8a7827f3546c7ac493dc114a14ab2"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_linux_arm64.tar.gz"
    end
  end

  name "specs"
  desc "General-purpose developer CLI"
  homepage "https://github.com/specsnl/specs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/specs"]
    end
  end

  # No zap stanza required

end
