# This file was generated by GoReleaser. DO NOT EDIT.
cask "specs@rc" do
  version "0.0.14-rc.3"

  on_macos do
    on_arm do
      sha256 "cb08c90d2be8fb11bb4b0f70b6650befad277b0958eede65fc385426b7fc87b7"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "933b23f38c6188884fbed1e70e7d1392d1128cae41fa675e9d1fa2a7f52df6fe"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "830656093cc5a204f9aaa5b3d402b0e081eab70e6bb573dd4150ef19c746f3f8"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a0d9f58cb1e6bd20aa0dadbaef91dd434a6e5377fe3a2e6a66486747b0394ef0"
      url "https://github.com/specsnl/specs-cli/releases/download/v#{version}/specs_linux_amd64.tar.gz"
    end
  end

  name "specs@rc"
  desc "General-purpose developer CLI"
  homepage "https://github.com/specsnl/specs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/specs"]
    end
  end

  # No zap stanza required
end
